### ISSUE TITLE
Class Extension Textbox with URL Validation 'Browse Assets' Doesn't Work

### ISSUE THREAD

**Issue by spill50** [blueriver/MuraCMS#1295]
When using a textfield with validation type url in a class extension, the 'Browse Assets' button does not work it throws the following JavaScript error:

`Uncaught TypeError: Cannot call method 'toLowerCase' of undefined`

**Comment by encipherdesign** [comment]
i can replicate this issue, i receive the same error:

   `Uncaught TypeError: Cannot call method 'toLowerCase' of undefined`

on the core admin js:  /admin/assets/js/admin.min.js?coreversion=6528

when attempting to use an extended attribute field with the URL validation on a Textbox input

the 'browse assets' button is rendered useless due to the error.

using the latest mura code: v. 6.2.6528

**Comment by PeterBowater** [comment]
Also seeing this issue with 6.2.6325, unable to Browse assets when using URL validation.
