### ISSUE TITLE
[/one/two/skip/a/few/default/includes/display_objects/formbuilder/dsp_form.cfm] not found

### ISSUE THREAD

**Issue by al3x-edge** [blueriver/MuraCMS#1812]
Full Stacktrace: https://gist.github.com/al3x-edge/754dd854c3882fd783d0

Currently have this error showing up on a site after upgrade.  Went back to a clean file backup from yesterday and it ran fine again. After another shot at upgrading, it's back down.  Nothing special done with the site except upgrading.

Upon inspection of the web folder after upgrade, there are files everywhere in the directory.  Screenshot:
![image](https://cloud.githubusercontent.com/assets/62131/6547438/9e7bd89e-c5ae-11e4-8776-db70e3791c26.png)

Versions:
![image](https://cloud.githubusercontent.com/assets/62131/6547459/37856e24-c5af-11e4-95f1-87b08ccc4226.png)

**Comment by mattlevine** [comment]
That's the first time we've seen this error.  Would you mind giving us access to this Mura instance?

**Comment by mattlevine** [comment]
Add this file to your local site

https://github.com/blueriver/MuraCMS/blob/master/default/includes/display_objects/formbuilder/dsp_form.cfm

**Comment by mattlevine** [comment]
One more question, are you using a shared display pool?

**Comment by al3x-edge** [comment]
@mattlevine Do you want to add the `dsp_form.cfm` after or before the upgrade? And no shared display pools as far as I know.  Most of our stuff is vps-separated and just stock Mura for the most part.

**Comment by mattlevine** [comment]
For some reason you last update attempt put all the files in the Mura root, which I have never heard of before. It may have to do with a mixed core version since in your screen shot it still says 6.1 

1. I would back everything up.
2. Delete your /config/version.cfm
3. Update your core once more.
4. After the core update refresh the page once more time and confirm that Mura says "6.2" under the admin settings"
5. Delete your /[siteid]/version.cfm
6. Update your site files.

**Comment by al3x-edge** [comment]
@mattlevine I'll be checking on this tonight.
