### ISSUE TITLE
Form embed with [mura] or dspObject() not working

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#1830]
Hi chaps (twice today, sorry!),

I use a mura-generated form to collect feedback for a site, across all pages, I use this bit of CFML to embed it in the template:

```ColdFusion
$.dspObject('form', 'Feedback Form')
````

Which allows you to view the form absolutely fine, but when submitting the form it just reloads and displays the form again, no thank you message or anything.

I assume this has come about due to the async loading of forms (6.1 was absolutely fine), so I had a quick poke about, but couldn't find anything obvious.

I also tried embedding the form in a component, using the [mura] tag, and then including the component in the template, but still no luck.

Thanks for you help!

Peter.

**Comment by stevewithington** [comment]
@PeterBowater, yep. This is definitely related to the new async ... we'll take a look.

**Comment by stevewithington** [comment]
@PeterBowater for now, I've submitted a temporary fix until we get a patch in place:
https://github.com/blueriver/MuraCMS/pull/1831

**Comment by PeterBowater** [comment]
Thanks very much Steve, will give it a try this morning!

Peter.

**Comment by sihu** [comment]
I found something very related to issue:
we have also a lot of forms made by "Add Form with Editor". i tried to make them work. but now i found a difference between the "Add Form with Form Builder" forms and the normal forms:

the forms built with the formBuilder are wrapped with a diff:

    <div class="mura-async-object" data-object="form" data-objectid="{formdata-content-id}" data-objectparams="{}" data-responsechart="0">{formdata}</div>

the Forms with Editor don't have this wrapping and because of that it's loading every time. i can imagine, the problem is somewhere in the logic where the display-objects are rendered and normal forms are not handeled the same as those from the formBuilder.

**Comment by mattlevine** [comment]
Can you give me access to the forms that are having the problem?  You can also add this to your /[siteid]/includes/contentRenderer.cfc:

this.asyncObjects=false;

**Comment by mattlevine** [comment]
In Mura 6.2 only forms built with Mura's form builder are asynchronous.  This is by design, too many many people have done too many custom things to change that process.   If you want your's to be asynchronous all you need to do is remove the "and isJSON()" from this line of code:

https://github.com/blueriver/MuraCMS/blob/develop/default/includes/display_objects/datacollection/index.cfm#L71

You would then copy your [siteid]/includes/display_objects/datacollection/index.cfm file over to your theme's display object directory:

 [siteid]/includes/themes/[theme]/display_objects/datacollection/index.cfm

And then in your typical dspInclude() that may be placed in the form's response text with the Mura tag your can reference the form.fieldnames from: 

```
$.event('formDataBean').getValue('fieldnames');
```

**Comment by CoenWarmer** [comment]
The temporary fix definitely works, great. Any news on a more definitive solution?
