### ISSUE TITLE
Json api user entity

### ISSUE THREAD

**Issue by tanyac** [blueriver/MuraCMS#1845]
I'm just having a play around with the JSON API, which looks really good. Only thing is that I can't seem to return any user data, unless logged in as an admin, which is understandable, but even trying to get the current user data results in an "Insufficient Account Permissions" error. 

Had a poke around in the code, and there is a check to see if the requested entity is the current logged in user but that then gets overridden by the `getBean('permUtility').getModulePerm(config.moduleid,variables.siteid); ` call. Is there something that I'm missing to return the user data?

Cheers
Tanya

**Comment by mattlevine** [comment]
For security reasons the JSON api is turned off by default.  Further, by default the user and group entities are not public (except for you own user entity).  It just seems like a bad idea to have a Mura instance's user data available without explicitly making that decision.

However you can make them public by editing their entityConfig during the site eventHandler's onApplicationLoad event

```
function onApplicationLoad($){
    $.siteConfig().getApi().getEntityConfig('user').public=true;
}
```

Or

```
function onApplicationLoad($){
    $.getBean('settingsManager')
        .getSite(siteid='yoursiteid')
        .getAPI()
        .getEntityConfig('user')
        .public=true;
}
```

As as side note I fixed a bug in relation to this so please update your core before testing it.

In addition you may want to only limit certain user fields to available via the api.  You can do this by setting the entityConfig "fields" setting to a list of the fields that you would want by default returned for the specific entity.

```
function onApplicationLoad($){
    var entityConfig=$.siteConfig().getApi().getEntityConfig('user');
    entityConfig.public=true;
    entityConfig.fields='username,fname,lname,company';
}
```

And finally, you may want to lock down the available fields so that people can't do custom fields selections:

Here's an example of doing a custom field selection:

```
http://domain.com/index.cfm/_api/json/[siteid]/user/?fields=username,fname,lname
```

To stop people from being able to do this you can set the allowfieldselect setting to false:
```
function onApplicationLoad($){
    var entityConfig=$.siteConfig().getApi().getEntityConfig('user');
    entityConfig.public=true;
    entityConfig.fields='username,fname,lname,company';
    entityConfig.allowfieldselect=false;
}
```

Overall the JSON api is still very new and will grow with it's use.  We've used it extensively with custom Mura ORM entities and basic content, but actually haven't used to to manage users.

Hopefully that helps,
-Matt

**Comment by tanyac** [comment]
Thanks for the info Matt, very helpful. We're investigating using the user API to connect with a very basic mobile app. So far, it looks quite promising.

Cheers
Tanya

**Comment by stevewithington** [comment]
Closing issue as resolved.
