### ISSUE TITLE
JSON API returning max 20 items

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#1865]
Hi,

Been playing with the JSON API as I think I may have a good use for it... however when making  call for content items with findquery method, I only receive 20 items in the JSON, I presume this is down to the default mura feed/iterator handling of only offering 20 items, however in my case I have over 200, and need them all returned.

I had a scope through the CFC but couldn't see anything where it was being restricted, or accepting an argument to allow me to specify the record numbers returned, even when using the findAll method.

Any thoughts?

TIA :)

Pete.

**Comment by stevewithington** [comment]
@PeterBowater Did you try adding &maxItems=x? to your call?

**Comment by stevewithington** [comment]
@PeterBowater If that doesn't work, try adding `&nextN=0`as well.

**Comment by PeterBowater** [comment]
With maxItems=9999 I still get 20 returned, with &nextN=0 I get just {"data":{"items":[]}} returned, whether I have maxItems set or not.

Also tried setMaxItems=9999 and setNextN= 0/9999 with no change, just returning 20 items still.

hmmm... bit more fiddling, think the issue in setFeedProps():

```ColdFusion
function setFeedProps(feed,$){

		if(len($.event('orderby'))){
			feed.setOrderBy($.event('orderby'));
		}

		if(len($.event('sortby'))){
			feed.setSortBy($.event('sortby'));
		}

		if(len($.event('sortdirection'))){
			feed.setSortDirection($.event('sortdirection'));
		}

		if(len($.event('maxitems'))){
			feed.setNextN($.event('maxitems'));
		}

		if(len($.event('size'))){
			feed.setMaxItems($.event('size'));
		}

		if(len($.event('limit'))){
			feed.setMaxItems($.event('limit'));
		}

		if(isNumeric($.event('isPublic'))){
			feed.setIsPublic($.event('isPublic'));
		}

		if($.event('entityName')=='content' && len($.event('type'))){
			feed.setType($.event('type'));
		}
	}
```

I think those 'setMaxItems()' should be 'setNextN()', I've tried this and it works locally.

You can, from that code, also use maxitems=, limit=, size=, and all should work to limit the number of returned records.

Cheers,


Pete.

**Comment by mattlevine** [comment]
Ok, I figured out that I was configuring the feed, but I wasn't configuring the return iterator.  In addition,  I added pageSize, pageNum, startRow and cachedWithin options.  For now don't use nextN since that is a column in the db so it end filtering for that value.

The cachedWithin takes the number of seconds that you would like the feed query to be cached.

**Comment by mattlevine** [comment]
I just refactored how some of this works.   Now all return array from the JSON api follow this format

```
{data: {
    startindex:1,
    endindex:10,
    totalitems:100,
    totalpages:10,
    itemsperpage:10,
    links:{
         first:'url for api call to get the first page of items',
         previous:'url for api call to get the previous page of items',
         self:'url for api call to get the the current of items',
         next:'url for api call to get the next page of items',
         last:'url for api call to get the last page of items',
        }
    }
}
```

So you can now use that data to say things like:

```
Showing {{data.startindex}} through {{data.endindex}} of {{data.totalitems}}
```

Or:

```
Showing {{data.pageindex}}  of {{data.totalpages}}
```

And then use the link values to transition to different pages.  The link values only exist when they are relevant.  So for example if you're on the first page there is not a 'prevous' link

In addition for sorting I added the ability to use + and - to determine ascending/descending.

So:
```
?sort=-title
```
will sort by title descending.

Also, I added itemsPerPage page size and pageIndex for setting the page of items in the result set to return.  'NextN' won't work for now since it's an actual filterable value in the content entity.  

So you can do this to pull the 
```
http://domain.com/index.cfm/_api/json/v1/[siteid]/[entityname]/?maxItems=100&itemsPerPage=10&pageIndex=4
````
To pull the 4th page of items.

And finally, I added caching to all of Mura's feed entities.  So you can do this:

```
it=$.getBean('feed')
    .loadBy(name='[feedName]')
    .setCachedWithin(createTimespan(0,0,0,5))
    .getIterator();
```

And the query underlining the iterator will be cached for the value of the timespan created.

And finally this is also now exposed via the json api with a 'cachedWithin' attribute which unlike a timespan object it is simply the number of seconds that you want the underlining query to be cached.

```
http://domain.com/index.cfm/_api/json/v1/[siteid]/[entityname]/?maxItems=100&itemsPerPage=10&pageIndex=4&cacheWithin=120
````

I've been wanting to do that for a while.

**Comment by davidpanzarella** [comment]
Really cool stuff, Matt! I really should show you our refactored search system again as its got a lot of the same feel.

**Comment by PeterBowater** [comment]
Ah Steve, thanks very much, sorry, for some reason I tend to miss github notifications, very cool stuff, and will certainly make life easier in future, much more lflexible implementation of remote content feeds.
