### ISSUE TITLE
Character limit in Body field when using SQL Server(?)

### ISSUE THREAD

**Issue by PeterBowater** [blueriver/MuraCMS#1922]
Guys,

I have recently tried copy pasting a LOT of content into the mura 'Content' field, but is got truncated once the content was saved.

It was around 312,000 characters (I know, I know!), and got truncated down to almost exactly 32,000, once I had accounted for CR, LF and spaces, so I quickly search the code, and find in en.properties:

sitemanager.content.fields.maxcharacters=(Max\=32000) Characters

I'm not sure this is actually enabled in this form, seems a slightly odd syntax, but possibly just not one I have come across before :)

Still, the wider issue is that when saving this amount of content locally, where I use MySQL, as opposed to SQL Server in production, it WORKS, all 312K characters get saved.

So not sure exactly what is going on, thought I would let you know.

Cheers,

Peter.

**Comment by jsieber-aca** [comment]
Hi Peter,
I've run into this problem in the past, but with MySQL. The fix for me was to increase the Long Text Buffer (chr) in the datasource defined within the Coldfusion administrator. Might not be the issue you are running into, but thought it might be worth suggesting. More info here: http://john-sieber.com/blog/mura-cms-content-truncated/
Hope this may help.
-John

**Comment by JonnyHayes** [comment]
CFADMIN > DSN > Enable long text retrieval (CLOB)

**Comment by PeterBowater** [comment]
Thanks both!

I used the second option, turning on the enable long text retrieval, and worked first time.

The data was saved successfully, it was when it was returning it to the editor or the published page it was being truncated, apparently :)

So not a mura issue, closing.

Thanks again,


Pete.
