### ISSUE TITLE
Mura 7.0.6754 Bug beanORM

### ISSUE THREAD

**Issue by dbudde** [blueriver/MuraCMS#2419]
I am getting a bug in the 'addQueryParam' method on line 305 for:

`if(listFindNoCase('int,tinyint',columns[arguments.prop.column].datatype)`

It appears it is not accounting for fields with possible NULL values.  The problem occurs for me when I have an object being saved with an 'int' field that the value has not been set.

**Comment by mattlevine** [comment]
Please update and retest.

**Comment by dbudde** [comment]
Looks to be corrected and working now.  Just below it the date portion works similarly.  Will it be susceptible to the same problem?

**Comment by mattlevine** [comment]
No, because that code only changes the cfsqltype on the query's param and not the value. Honestly, the line code where the issue was happening probably is probably not needed, but there was a weird Postgres issue where a value passed isNumeric() but would not validate with the integer query param type. Which is weird.
