### ISSUE TITLE
Issue with loading assets!!!

### ISSUE THREAD

**Issue by rawadtan** [blueriver/MuraCMS#2432]
I am new to Mura CMS, after installing Mura Code Base & accessing admin & front-end pages I noticed that the resources are not loaded, and my app name is duplicated within each resource URL, like the example below, **getgroup** 2 times, any help please!!!
![image](https://cloud.githubusercontent.com/assets/16817900/19464119/ac120ce4-950a-11e6-8284-66991510526b.png)

**Comment by mattlevine** [comment]
Can you check the value of the context and assetpath attributes in your /config/settings.ini.cfm?

If Mura is  in a sub directory the should match it /getgroup, otherwise they souls be an empty string. You'll need to reload Mura by putting ?appreload out in the URL in order to see any new settings get loaded on not the app as well.

**Comment by rawadtan** [comment]
Thanks mattlevine
I deleted the value of the context attribute & it works perfectly now
