### ISSUE TITLE
erro when installing latest version

### ISSUE THREAD

**Issue by ingelamote** [blueriver/MuraCMS#2469]
I got following error when installing mura when installing mura version 7.0.6840:
 Attribute validation error for tag CFCOOKIE.
Type: Template
It has an invalid attribute combination: expires,httponly,name,path,preservecase,value. Possible combinations are:<li>Required attributes: 'name'. Optional attributes: 'domain,encodevalue,expires,httponly,preservecase,secure,value'. <li>Required attributes: 'domain,name,path'. Optional attributes: 'encodevalue,expires,httponly,preservecase,secure,value'.

**Comment by mattlevine** [comment]
This is now fixed with this commit:
https://github.com/blueriver/MuraCMS/commit/ab52663ce10af7d7765dc7ce3a228a0693d09421

I also added a unit test to prevent this issue from popping up again
https://github.com/blueriver/MuraCMS/commit/a57887ac1d28ad4e7a7c32e4970fe4bc21485e64

Please manually update this file:

https://github.com/blueriver/MuraCMS/blob/master/requirements/mura/utility.cfc

And manually reload Mura by making a request in your browser to the Mura root with ?appreload

-Matt
