### ISSUE TITLE
Where do I get Mura Express?

### ISSUE THREAD

**Issue by parkej60** [blueriver/MuraCMS#2471]
In reading through the documentation I came across the Mura Express option. Within that documentation it states, 

> Mura Express is used primarily for training purposes and not recommended for use in production environments. This version of Mura is not currently available for public download. For production environments, we recommend following the instructions for Installing the Mura Code Base.

Is there a way to get Mura express through some other means?

**Comment by PeterBowater** [comment]
I believe the Express edition got nixed somewhere around 6.2.

If you want to get up and running quickly though, I can recommend using Commandbox:

https://www.ortussolutions.com/products/commandbox

Allows you to run against version of CF, Railo and Lucee all from one tool.

Installing Mura Express is just a case of unzipping the contents of the repo into a folder and running up a box.

**Comment by stevewithington** [comment]
It's just Mura, running on Lucee Express, with the embedded H2 database
option.

We don't keep an up to date version of it for the general public. I simply
create a version anytime I have an upcoming training class.

Cheers,
Steve

On Dec 12, 2016 4:47 PM, "James Parker" <notifications@github.com> wrote:

In reading through the documentation I came across the Mura Express option.
Within that documentation it states,

Mura Express is used primarily for training purposes and not recommended
for use in production environments. This version of Mura is not currently
available for public download. For production environments, we recommend
following the instructions for Installing the Mura Code Base.

Is there a way to get Mura express through some other means?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/blueriver/MuraCMS/issues/2471>, or mute the thread

**Comment by parkej60** [comment]
Is there a free / developer version of ColdFusion that I can install on my local machine for development purposes? Or can I run Mura on Lucee or Railo without ColdFusion? Sorry for the questions, new to this stack and trying to get a test environment setup to explore for a client.

Jameson W Parker

**Comment by PeterBowater** [comment]
I told you above how to do that, with commandbox.

**Comment by parkej60** [comment]
Ok, I wasn't sure if I still needed CF with that tool and just wanted to verify.

Jameson W Parker

**Comment by seanschroeder** [comment]
Hi Jameson,

Just to be clear, Lucee is a free, open source alternative to Adobe ColdFusion. You can install Mura with your DB of choice (mysql, postgres, oracle) and Lucee, including Lucee Express which has an embedded H2 database.

Does this make sense?

**Comment by fraxen** [comment]
Jameson,  you can also install Adobe ColdFusion (ACF) with the trial install, that will revert to an IP-restricted developer edition after 30 days. Saw on Adobe's pages now that there is also a developer oriented "ACF Express" edition as well, not sure what that is about. (Personally I am all Lucee...)

**Comment by parkej60** [comment]
Yes, that is exactly the answer I was looking for!

Jameson W Parker

**Comment by stevewithington** [comment]
Lucee (http://lucee.org) is an open source CFML engine, an alternative to
Adobe's ColdFusion offering.

Railo is no longer being developed, as the vast majority of its development
team are the ones behind Lucee.

Hope that makes sense.
