### ISSUE TITLE
CKEditor's Add Internal Link and Insert Component no longer work with a separate admin domain

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2701]
The recent addition of `dialogdef.dialog.on('show'...` in `requirements/ckeditor/config.js.cfm` added a new bug for Mura configurations using `admindomain` when _Full Edit_ is used.
`parent.document.getElementById` fails because of a cross-origin restriction, and subsequent events are not processed. As a result, the editor iframes for Add Internal Link and Insert Component are never loading, and the dialogs are empty. No error occurs when Inline Edit is used instead of Full Edit.

`window.top.document.addEventListener("keydown", checkForSave , false);` similarly fails in `admin/core/views/carch/edit.cfm`. There is another similar error in `ckfinder.js`.

**Comment by mattlevine** [comment]
Thanks for the heads up.  We're looking into the dialogdef and addEventListener issues.  However, CKFinder is now cross domain compatible and since it's not our project and they have EOL CF support we have no plans to address that part.  We are however, planning to replace CKFinder entirely and we'll definitely look for cross domain support with it's replacement.

**Comment by damien-git** [comment]
No problem, I expected that. One practical issue I noticed with CKFinder is that the CKFinder window does not close automatically after a double-click on an item. This is a minor issue.

**Comment by damien-git** [comment]
We just noticed another issue that seems to be caused by the CKFinder error: it is not possible to configure a folder display object (parameter changes have no effect).
