### ISSUE TITLE
Admin site selection menu not usable with many sites

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2716]
This looks like a regression from Mura 6. We manage about a hundred sites in a single Mura instance, so we need the site selection menu to scroll when there are many sites.
In Mura 7, this menu has no scrollbar, so some menu items cannot be reached.
Also, a search box appears starting at 21 sites, but it is not functional: the menu disappears when you click on it.

**Comment by stevewithington** [comment]
@damien-git thanks for the heads up on this ... we'll take a look

**Comment by gowestweb** [comment]
Pushing up a fix for this now.

**Comment by damien-git** [comment]
Thanks for the fix. Will this be pushed to Mura 7.0 ?

**Comment by mattlevine** [comment]
Yes, it's in the latest 7.0 build now.

**Comment by damien-git** [comment]
I was confused because there is no scrolling, it looks like the update only adds a search box. Would it be possible to add scrolling like in Mura 6 ?

**Comment by earleyj1** [comment]
As @damien-git stated, would it be possibly to allow the list to scroll? Looking at Mura 6, the list has the following CSS to allow for that:

    max-height: 200px;
    overflow-y: auto;

It seems like a simple addition. We have roughly 100 sites, and we can't scroll through the list. Since Mura 7 has larger font for the site list, changing the max-height property to something larger would also help.
