### ISSUE TITLE
Mura 7.1 installation fails (bug) 

### ISSUE THREAD

**Issue by tomysaman** [blueriver/MuraCMS#2805]
Version: 7.1

Error: source file [/...../config/settings.ini.cfm] is not a file

Traces:
/core/mura/IniFile.cfc line: 63
/core/setup/inc/doa/DBController.cfc line: 135 

How to replicate:
Run the Mura installation wizard and submit your setup settings

Reason:
When constructing the path to settings.ini.cfm, the codes haven't been updated to account the directory structure changes from Mura 7.0 to 7.1

https://github.com/blueriver/MuraCMS/blob/7.1/core/setup/inc/doa/DBController.cfc#L128

`this.baseDir = left(getDirectoryFromPath(getCurrentTemplatePath()),len(getDirectoryFromPath(getCurrentTemplatePath()))-22);`

Removing the last 22 characters is too many for 7.1 because the path from DBController.cfc is
"/...../core/setup/inc/doa/" 

Instead of 22 chars, it should be 19 chars

**Comment by cfmitrah** [comment]
Hi @tomysaman,
In line:128
this.baseDir = left(getDirectoryFromPath(getCurrentTemplatePath()),len(getDirectoryFromPath(getCurrentTemplatePath()))-22);
Changing the chars(19) will create file path for "settings.ini.cfm"
like

` "D:\Projects\testInstall\MuraCMS\/config/settings.ini.cfm"`

 because of the concatenation in

Line:129 :: '`this.settingsPath = this.baseDir & "/config/settings.ini.cfm";`'

so changing the chars(20) in line:128, and changing line:129 as
'`this.settingsPath = this.baseDir & "\config\settings.ini.cfm";`'
will create Path

 "`D:\Projects\testInstall\MuraCMS\config\settings.ini.cfm`"

and I have created PR `for` the fix
PR:https://github.com/blueriver/MuraCMS/pull/2806

**Comment by tomysaman** [comment]
Thanks @cfmitrah 
Closing ticket
