### ISSUE TITLE
Upgrade Admin's jquery-ui

### ISSUE THREAD

**Issue by jamiejackson** [blueriver/MuraCMS#2878]
We got dinged in a security scan for a core admin asset. We're pulling from the `7.0` branch.

---

Vulnerable Javascript library
Severity: Medium
Reported by module Scripting: (Javascript_Libraries_Audit.script)

Description: 
You are using a vulnerable Javascript library. One or more vulnerabilities were reported for this version of the Javascript library.
Consult Attack details and Web References for more information about the affected library and the vulnerabilities that were reported.

Impact:
Consult References for more information.

Recommendation:
Upgrade to the latest version.

Affected items:
/admin/assets/js/jquery/jquery-ui.min.js\

Details
Detected Javascript library jquery-ui-dialog version 1.11.4.
The version was detected from file content.
```
GET /admin/assets/js/jquery/jquery-ui.min.js HTTP/1.1
/jquery/jquery-ui.min.js HTTP/1.1
Pragma: no-cache
Cache-Control: no-cache
Referer: https://mysite.com/admin/index.cfm
Cookie: cfid=0bd69eb5-8528-4123-accc-e872fd44b343; cftoken=0; JSESSIONID=CB6AECEA680B1E78FF2C9BE655ABBB2A; MXP_TRACKINGID=B1BBB96D-FE0A-4584-85896DF5F19DA8AF; mobileFormat=false; RB=pt; ADMINSIDEBAR=off
Host: mysite.com
Connection: Keep-alive
Accept-Encoding: gzip,deflate
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.21
Accept: /
```

**Comment by mattlevine** [comment]
FYI, we started this and it should be out next week.

**Comment by mattlevine** [comment]
jQueryUI and jQuery have been updated in both 7.1 and 7.0.  However, the version of jQuery in the /default/js/external directory was only updated to the latest 2.x branch due to the fact that the Bootstrap3 does not support jQuery 3.  This is only an issue with 7.0 as 7.1 does not have this file.  So if that's an issue I would manually add jQuery 3 to your theme and add it to your theme's templates/inc/html_head.cfm

https://github.com/blueriver/MuraBootstrap4/blob/master/templates/inc/html_head.cfm#L29

Mura will see it and not load the the {siteid}/js/external one.
