### ISSUE TITLE
Upgrade jquery.min.js

### ISSUE THREAD

**Issue by ajays28** [blueriver/MuraCMS#2882]
Vulnerable Javascript library.
Our security scan detected an older version of jquery.min.js (2.2.2) file. We're pulling from the 7.0 branch.
(related issue: Upgrade Admin's jquery-ui #2878)

<hr/>

Vulnerable Javascript library
Severity: Medium
Reported by module: Scripting (Javascript_Libraries_Audit.script)

Description
You are using a vulnerable Javascript library. One or more vulnerabilities were reported for this version of the Javascript library.
Consult Attack details and Web References for more information about the affected library and the vulnerabilities that were reported.

Impact: Consult References for more information.

Recommendation: Upgrade to the latest version.

Affected items: /js/external/jquery.min.js

Details: 
Detected Javascript library jquery version 2.2.2.
The version was detected from file content.
References:
https://github.com/jquery/jquery/issues/2432

<code>
Request headers
GET /js/external/jquery.min.js HTTP/1.1
Accept: */*
Referer: https://mysite.com
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.21 (KHTML, like Gecko)
Chrome/41.0.2228.0 Safari/537.21
Cookie: JSESSIONID=05E01596F7D3121F965; 
mobileFormat=false; cfid=f882-444e-af12-3ad716226691; cftoken=0
Connection: Keep-alive
Accept-Encoding: gzip,deflate
Accept-Language: en-US,*
Host: mysite.com
Pragma: no-cache
Cache-Control: no-cache
</code>

**Comment by mattlevine** [comment]
jQueryUI and jQuery have been updated in both 7.1 and 7.0.  However, the version of jQuery in the /default/js/external directory was only updated to the latest 2.x branch due to the fact that the Bootstrap3 does not support jQuery 3.  This is only an issue with 7.0 as 7.1 does not have this file.  So if that's an issue I would manually add jQuery 3 to your theme and add it to your theme's templates/inc/html_head.cfm

https://github.com/blueriver/MuraBootstrap4/blob/master/templates/inc/html_head.cfm#L29

Mura will see it and not load the the {siteid}/js/external one.

**Comment by ajays28** [comment]
Thank you, Matt.
